---

- name: Ensure MySQL installed
  become: yes
  become_method: sudo
  yum: name={{ item }} state=present
  with_items:
    - mariadb
    - mariadb-server
    - MySQL-python

- name: Copy /etc/my.cnf
  become: yes
  become_method: sudo
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: restart mysql

- name: Start MySQL service
  become: yes
  become_method: sudo
  service: name=mariadb state=started enabled=yes
